apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-cicd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Andersoncrs5/cicd-app-example.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: node-cicid-app 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:              
      - CreateNamespace=true  