pipeline {
    agent {
        kubernetes {
            yamlFile 'node-cicd-app/k8s/setup.yaml'
            defaultContainer 'node'
        }
    }

    stages {
        stage('Install & Test') {
            steps {
                container('node') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }
        
        stage('Build with Kaniko') {
            steps {
                container('kaniko') {
                    echo "Aqui entraremos com o comando do Kaniko no próximo passo..."
                }
            }
        }
    }
    post {
        success {
            echo '✅ Pipeline executado com sucesso!'
        }

        failure {
            echo '❌ Pipeline falhou! Verifique os logs.'
        }

        always {
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                    echo "🎉 Deploy concluído"
                } else {
                    echo "⚠️ Algo deu errado"
                }
            }
        }
    }
}