pipeline {
    agent {
        kubernetes {
            yamlFile 'node-cicd-app/k8s/setup.yaml'
            defaultContainer 'node'
        }
    }

    stages {
        stage('Install & Test') {
            steps {
                dir('node-cicd-app') {
                    container('node') {
                        sh 'npm install'
                        sh 'npm test'
                    }
                }
            }
        }
        
        stage('Build with Kaniko') {
            when {
                branch 'main'
            }
            steps {
                container('kaniko') {
                    sh """
                    /kaniko/executor --context ${WORKSPACE}/node-cicd-app \
                    --dockerfile ${WORKSPACE}/node-cicd-app/Dockerfile \
                    --destination andersoncrms/node-cicd-app:v${env.BUILD_NUMBER} \
                    --destination andersoncrms/node-cicd-app:latest
                    """
                }
            }
        }
    }
    post {
        success {
            echo '✅ Pipeline executado com sucesso!'
        }

        failure {
            echo '❌ Pipeline falhou! Verifique os logs.'
        }

        always {
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                    echo "🎉 Deploy concluído"
                } else {
                    echo "⚠️ Algo deu errado"
                }
            }
        }
    }
}